name: Docker Image CI

on:
  push:
    branches: [ main, snapshot ]
  pull_request:
    branches: [ main, snapshot ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag customer-service:$(date +%s)
